### ISSUE TITLE
Unable to use special characters in clozes

### ISSUE THREAD

**Issue by 21eleven** [Mochitto/Markdown2Anki#5]
Anki itself allows any characters within clozes (with the exception of `::` I believe).

For example, I may ave a note/card like:
```
---
## order preserving function

for a function f: ℝ -> ℝ 
- f is said to be **{{c1::order preserving}}** if **{{c2::a < b implies f(a) < f(b)}}**
---
```
Which doesn't seem like unusual information to put within a card. However Markdown2Anki will not create notes that have this content within a cloze.

**Comment by Mochitto** [comment]
Hey there! Thank you for checking out the project and helping with it :)

I've looked into the issue and I think I solved the problem in the last patch:
Issue: #1 
Change log: https://github.com/Mochitto/Markdown2Anki/blob/master/CHANGELOG.md#020---2023-04-19

---

I tried out your specific case and it seems to work now! Hints also work, so you can have clozes in the form of `{{c1::something::hint}}` as well :)
![image](https://user-images.githubusercontent.com/98263539/234184030-c33a3ba3-a8a2-4821-8515-7dd39d1d9667.png)

You should be able to upgrade to it using
`pip install markdown2anki -U`

---

There should be a feature that lets you know new versions are available; did it not work? :o 
It will skip the check if your connection is slower or missing as well, to avoid long starting times.

Let me know if that seems to fix it!
If not, it would be very helpful if you could let me know what version you are currently running, so I can look into it better.

**Comment by 21eleven** [comment]
Aha! I needed to update :smile: 

> There should be a feature that lets you know new versions are available

I can confirm this is working for me

> Hints also work

:raised_hands: awesome!

Thanks for the great tool!
